CREATE DATABASE IF NOT EXISTS lingvo;
USE lingvo;
DROP TABLE IF EXISTS result;
CREATE TABLE result (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	origin VARCHAR(40), norm VARCHAR(40) DEFAULT NULL, correct VARCHAR(40) DEFAULT NULL, gram VARCHAR(40) DEFAULT NULL) DEFAULT CHARACTER SET utf8;
SELECT * FROM result;
